### ISSUE TITLE
Yazu spinning on load after deleting Zibo 737

### ISSUE THREAD

**Issue by brady-sewall** [xairline/yazu#2]
M1 MacBook Pro running MacOS Sonoma 14.3.1
Yazu 1.0 (also tried 1.1.2 pre-release)
X-Plane 11 and 12, but trying X-Plane 11 first.

I just found Yazu today and ran it this morning. It updated my Zibo 737 to the latest version. Launched X-Plane 11 and noticed some bugs - the center display was saying something about "out of date" and "discard". Looking at the external display, the engines were not spinning, although they were running in the sim.

Thinking a fresh start would be better, I deleted the Zibo 737 and re-ran Yazu. Upon doing this Yazu opens, but has a spinning/loading icon. I even used an App Cleaner to remove Yazu (so it removes the associated preferences too) and re-installed Yazu. Same result - the spinning/loading icon.

**Comment by brady-sewall** [comment]
Manged to restore a backup of an older Zibo 737 and re-ran Yazu. It loaded fine this time.

When I tell Yazu to re-install Zibo for a fresh start, it does, but then X-Plane 11 throws an error about generating path for aircraft preview and won't load.
![image](https://github.com/xairline/yazu/assets/38672484/800761a9-3832-49ab-8564-db4746116a18)

Restoring the backup again and updating to the latest version 4.01.6 does work, but the displays don't look correct and in an external view, the engines are not spinning although they are running.
![image](https://github.com/xairline/yazu/assets/38672484/4e713c91-92c2-41b5-8819-cebd3f625c89)

**Comment by zodiac1214** [comment]
yazu doesn't not support xp11. I simply download the XP 12 version. So it basically installed xp 12 version of zibo for you
